// One-line, factual "what they build" blurbs keyed by kebab(company). Hand-curated —
// gives the /company/[slug] page a fact the company's OWN careers page assumes you already
// know (the differentiator for the "{company} careers/jobs" navigational query we rank for),
// and feeds hiringOrganization.description in the JobPosting JSON-LD. Keep factual; omit if unsure.
export const COMPANY_BLURB = {
  // frontier / foundation-model labs
  anthropic: "Frontier AI lab building the Claude models — training and serving large models at scale.",
  openai: "Frontier AI lab behind GPT and ChatGPT — training and inference at massive scale.",
  xai: "Frontier AI lab building Grok, with large training clusters and inference infrastructure.",
  "mistral-ai": "European frontier lab known for its open-weight large language models.",
  cohere: "Enterprise LLM provider — model training and inference for business use.",
  "thinking-machines": "AI research lab founded by former OpenAI leadership.",
  perplexity: "AI answer engine combining retrieval with large-scale model inference.",
  "reka-ai": "Multimodal frontier-model research lab.",
  "liquid-ai": "Foundation-model lab building efficient post-transformer architectures.",
  "character-ai": "Consumer platform for conversational AI characters — very high-volume inference.",
  poolside: "Foundation models specialized for software development.",
  cursor: "AI code editor (Anysphere) — retrieval and low-latency model serving.",
  cognition: "AI software-engineering agent (Devin).",
  "magic-dev": "Frontier code models with very long context.",
  "world-labs": "Spatial-intelligence lab building large world models.",
  // generative media
  "black-forest-labs": "Generative image models (the FLUX family).",
  krea: "Generative-media creative tools built on real-time inference.",
  fal: "Generative-media inference platform for fast image and video models.",
  runway: "Generative video models and creative tools.",
  "inworld-ai": "AI engine for real-time characters and agents.",
  cartesia: "Real-time voice and audio AI models.",
  // AI-accelerator silicon
  "cerebras-systems": "Wafer-scale AI accelerators and the systems software around them.",
  tenstorrent: "AI-accelerator silicon plus the kernel and compiler stack for it.",
  sambanova: "Reconfigurable dataflow AI accelerators (RDUs) and full-stack systems.",
  graphcore: "UK AI-accelerator company (IPUs) with its own compiler and kernel stack.",
  "d-matrix": "Digital in-memory-compute accelerators for AI inference.",
  etched: "Transformer-specific ASIC (Sohu) built for ultra-fast inference.",
  matx: "AI-accelerator silicon optimized for large language models.",
  "encharge-ai": "Analog in-memory-computing AI accelerator chips.",
  lightmatter: "Photonic computing for AI — light-based interconnect and accelerators.",
  // GPU cloud / compute
  coreweave: "GPU cloud provider operating large accelerator fleets for AI.",
  nebius: "AI-centric cloud with its own GPU infrastructure.",
  crusoe: "Energy-first AI cloud building GPU data centers.",
  lambda: "GPU cloud and deep-learning workstations.",
  "together-ai": "GPU cloud and inference platform for open models.",
  "vast-ai": "Marketplace for renting GPU compute.",
  runpod: "GPU cloud for AI training and inference.",
  fluidstack: "GPU cloud aggregator for large-scale AI clusters.",
  "sf-compute": "Marketplace for large blocks of GPU compute.",
  "prime-intellect": "Decentralized AI training and compute.",
  tensorwave: "AMD-GPU cloud for AI workloads.",
  parasail: "On-demand AI inference network.",
  // inference / serving / platforms
  "fireworks-ai": "Fast inference platform for generative-AI models.",
  baseten: "Model inference and deployment platform.",
  modal: "Serverless cloud for AI and data workloads.",
  anyscale: "Creators of Ray — distributed compute for AI.",
  friendliai: "Generative-AI inference-serving engine.",
  "featherless-ai": "Serverless inference for a large catalog of open models.",
  sieve: "Video-understanding and media-AI infrastructure.",
  "lightning-ai": "Creators of PyTorch Lightning — an AI training and deployment platform.",
  // data / eval / autonomy / robotics
  databricks: "Data and AI platform (Lakehouse, Mosaic AI) — large-scale ML systems.",
  "scale-ai": "Data platform for AI plus model evaluation and infrastructure.",
  "applied-intuition": "Autonomy and ADAS software, heavy on simulation and ML systems.",
  "physical-intelligence": "Foundation models for robotics.",
};
